services:
  yt-dlp-webui:
    build: .
    environment:
      - JWT_SECRET=YmhS5P4VbZLqGdS71ZEmQd0Hv3KiDAaI # 请替换为您的实际 JWT 密钥
    ports:
      - 3033:3033
    volumes:
      - <your dir>:/downloads # replace <your dir> with a directory on your host system
      - <your dir>:/config # directory where config.yml will be stored
    healthcheck:
      test: curl -f http://localhost:3033 || exit 1
    restart: unless-stopped
